plugins {
    id 'com.android.application'
}

android {
    namespace 'com.infinix.tool'
    compileSdk 34

    defaultConfig {
        applicationId "com.infinix.tool"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
